### ISSUE TITLE
got err on NetworkImage on odoo 14

### ISSUE THREAD

**Issue by budisentosa** [ERP-Ukraine/odoo-rpc-flutter-demo#1]
```  
Widget buildListItem(BuildContext context, Map<String, dynamic> record) {
    var unique = record['__last_update'] as String;
    unique = unique.replaceAll(RegExp(r'[^0-9]'), '');
    final avatarUrl =
        '${context.read<OdooClient>().baseURL}/web/image?model=res.partner'
        '&field=image_128&id=${record["id"]}&unique=$unique';
    return ListTile(
      leading: CircleAvatar(backgroundImage: NetworkImage(avatarUrl)),
      title: Text(record['name']),
      subtitle: Text(record['email'] is String ? record['email'] : ''),
    );
  }
```

i think because on request get , you not include session_id on header

**Comment by lem8r** [comment]
Looks like you're trying to get non-public image.
With rpc lib you can download image data by reading datas field of corresponding ir.attachment record. Or make image public (or generate access token) and use url with NetworkImage.

**Comment by aungmyint** [comment]
How to know image is public or not. When i open image url in browser, it is ok. But when I call image url in postman, error message (404 Not found) shows.

**Comment by lem8r** [comment]
Attachments have boolean field for that as well access_token https://github.com/odoo/odoo/blob/16.0/odoo/addons/base/models/ir_attachment.py#L404-L407
It is not related to rpc library. The library only manages requests and session.

**Comment by aungmyint** [comment]
Thank you for your reply. I changed public field value to true and added value in access_token field for this image in ir_attachment table. When i call this image url in NetworkImage, show error message (404 not found exception).I use odoo version 11. Please advise me, How to do that?
